### ISSUE TITLE
Could not run pocketbase on windows 11

### ISSUE THREAD

**Issue by RayyanNafees** [benallfree/gobot#6]
# Error

![image](https://github.com/benallfree/gobot/assets/59685062/820dbabd-4c9d-4b68-8955-1da2518c855e)

# OS Info 
![image](https://github.com/benallfree/gobot/assets/59685062/bf8f0f0d-3e5a-42d2-862a-3e2b3471e697)

**Comment by benallfree** [comment]
Will be fixed in next alpha... for now `npx gobot 'pocketbase/pocketbase'` works :)

**Comment by RayyanNafees** [comment]
Still not working on windows:

Getting the following error:
```pwsh
Need to install the following packages:
gobot@1.0.0-alpha.35
Ok to proceed? (y)
Fetching info for pocketbase/pocketbase releases page 1...https://api.github.com/repos/pocketbase/pocketbase/releases?per_page=100&page=1
Fetching info for pocketbase/pocketbase releases page 2...https://api.github.com/repos/pocketbase/pocketbase/releases?per_page=100&page=2
Fetching info for pocketbase/pocketbase releases page 3...https://api.github.com/repos/pocketbase/pocketbase/releases?per_page=100&page=3
Downloading https://github.com/pocketbase/pocketbase/releases/download/v0.22.8/pocketbase_0.22.8_windows_amd64.zip
Downloading.............
Download completed.
Unpacking C:\Users\nafee\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.8\x64\win32\pocketbase_0.22.8_windows_amd64.zip
Error: Could not find pocketbase.exe anywhere in path C:\Users\nafee\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.8\x64\win32
```
## Screenshot

![image](https://github.com/benallfree/gobot/assets/59685062/6e25d870-8d7d-4c66-84cd-427cef10851c)

**Comment by benallfree** [comment]
Can you show me what's in `C:\Users\nafee\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.8\x64\win32`

**Comment by benallfree** [comment]
Also, try this:

```bash
npx gobot@latest reset pocketbase
npx gobot@latest pocketbase --help
```

**Comment by VictorioBerra** [comment]
This appears to be the same error as this https://github.com/benallfree/gobot/issues/4

@benallfree was this fixed?

**Comment by VictorioBerra** [comment]
See @RayyanNafees last line:

> Error: Could not find pocketbase.exe anywhere in path C:\Users\nafee\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.8\x64\win32

that is the exact same error I get.

**Comment by benallfree** [comment]
@VictorioBerra Can you please show me the directory listing for `C:\Users\nafee\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.8\x64\win32`

**Comment by VictorioBerra** [comment]
@benallfree that is nafee, mine is:

```
file:///C:/Users/toryb/source/repos/Failreactor-Pocketbase%20-%20JS/node_modules/gobot/dist/chunk-Y2WPSBSM.js:406
      throw new Error(`Could not find ${this.binName} anywhere in path ${path}`);
            ^

Error: Could not find pocketbase.exe anywhere in path C:\Users\toryb\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.7\x64\win32
    at _Gobot.findArchiveBinPath (file:///C:/Users/toryb/source/repos/Failreactor-Pocketbase%20-%20JS/node_modules/gobot/dist/chunk-Y2WPSBSM.js:406:13)
    at _Gobot.getBinaryPath (file:///C:/Users/toryb/source/repos/Failreactor-Pocketbase%20-%20JS/node_modules/gobot/dist/chunk-Y2WPSBSM.js:457:34)
    at async _Gobot.run (file:///C:/Users/toryb/source/repos/Failreactor-Pocketbase%20-%20JS/node_modules/gobot/dist/chunk-Y2WPSBSM.js:540:19)

Node.js v20.9.0
[nodemon] app crashed - waiting for file changes before starting...
```

directory listing

```
PS C:\Users\toryb\source\repos\Failreactor-Pocketbase - JS> dir C:\Users\toryb\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.7\x64\win32


    Directory: C:\Users\toryb\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.7\x64\win32


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         4/10/2024   1:37 PM              0 CHANGELOG.md
-a----         4/10/2024   1:37 PM           1090 LICENSE.md
-a----         3/29/2024   7:35 PM       41448960 pocketbase.exe
-a----         4/10/2024   1:37 PM       14709671 pocketbase_0.22.7_windows_amd64.zip


PS C:\Users\toryb\source\repos\Failreactor-Pocketbase - JS> 
```

**Comment by benallfree** [comment]
Interesting, so it's there but it's not finding it... I'll look into it more

**Comment by VictorioBerra** [comment]
@benallfree Not sure if this helps, but this works for me:

Change this line https://github.com/benallfree/gobot/blob/main/src/Gobot.ts#L232 

`const fname2 = globSync(join(path, this.binName), { nodir: true })[0];`

(remove the `**`):

**Comment by benallfree** [comment]
Interesting, I'm not sure that would search subdirectories if it were missing.

**Comment by VictorioBerra** [comment]
@benallfree I dont claim for it to be a fix, only to maybe help aid you in debugging.

**Comment by RayyanNafees** [comment]
> @benallfree Not sure if this helps, but this works for me:
> 
> Change this line [`main`/src/Gobot.ts#L232](https://github.com/benallfree/gobot/blob/main/src/Gobot.ts?rgh-link-date=2024-04-10T18%3A50%3A37Z#L232)
> 
> `const fname2 = globSync(join(path, this.binName), { nodir: true })[0];`
> 
> (remove the `**`):

@benallfree can u apply this as fix for now in the version so it works for now on Windows ?

Also.. seems like the package cannot execute anymore 
![{090346D3-B7D8-436C-B194-5D271FEA4662}](https://github.com/user-attachments/assets/f316af1a-a514-4a06-8175-f3af556aaa1d)

**Comment by benallfree** [comment]
I'll need to look into this more, I don't have Windows for testing so it's a bit difficult.

Also, I think gobot is evolving more toward an `esbuild` approach where the binaries are published on NPM. Are you able to try https://www.npmjs.com/package/gobot-pocketbase to see if that works any better?
